services:
  postgres:
    container_name: go-course-pg
    image: postgres:18.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres  
    ports:
      - "5432:5432"
    volumes:
      - go-course-pg:/data/postgres
  
  pgAdmin:
    container_name: go-course-pgAdmin
    image: dpage/pgadmin4:9.12
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - go-course-pgAdmin:/var/lib/pgadmin

volumes:
  go-course-pg:
  go-course-pgAdmin:
